_target_: src.models.regressor.RegressorModel2

net:
  _target_: src.models.components.base.RegressorNet2
  backbone:
    _target_: torchvision.models.resnet18 # change models on this
    pretrained: True
  bins: 2

lr: 0.0001
momentum: 0.9
w: 0.4
alpha: 0.6