_target_: src.models.regressor.RegressorModel

net:
  _target_: src.models.components.base.RegressorNet
  backbone:
    _target_: torchvision.models.mobilenet_v3_small # change models on this
    pretrained: True
  bins: 2

optimizer: adam

lr: 0.001
momentum: 0.9
w: 0.4
alpha: 0.6