_target_: src.datamodules.components.kitti_dataset.KITTIDataset3

dataset_path: ${paths.data_dir}
dataset_sets: ${paths.data_dir}/train_80.txt
bins: 2
overlap: 0.1
image_size: 224
categories: 
  - "car"
  - "pedestrian"
  - "cyclist"